### ISSUE TITLE
Use a bigger vm instance by default

### ISSUE THREAD

**Issue by bodymindarts** [genesis-community/bosh-genesis-kit#1]
[here](https://github.com/genesis-community/bosh-genesis-kit/blob/master/base/params.yml#L5) we are specifying `bosh_vm_type: small` but probably the default vm to be used needs to have more power than what is typically considered a 'small' vm.

In the aws-init subkit for example we are using `m3.xlarge`.

**Comment by geofffranks** [comment]
We've had no problems running bosh on Azure on an `A1_v2` (1cpu, 2gb memory) and `D1_v2` (1cpu, 3.5gb memory). I'm guessing the aws-init subkit should probably be updated to use a smaller default size. Seems like `m3.medium` should suffice.

**Comment by bodymindarts** [comment]
Well making the AWS default size a `m3.medium` still isn't really `small`.

**Comment by ramonskie** [comment]
maby the ability to set the instance type would be better
