### ISSUE TITLE
Feature: Remove Dev Tools by Default

### ISSUE THREAD

**Issue by jhunt** [genesis-community/bosh-genesis-kit#101]
I propose that we remove the dev tools on all VMs deployed by any Genesis BOSH director, by default.  People who want those tools can always re-add them.

See https://github.com/cloudfoundry/bosh/blob/master/jobs/director/spec#L153-L155

**Comment by rkoster** [comment]
Figure out how this relates to `env.bosh.{remove_dev_tools,remove_static_libraries}`: https://bosh.io/docs/manifest-v2/#instance-groups
