### ISSUE TITLE
Kit runtime-config addon uses update-config

### ISSUE THREAD

**Issue by michaelmccaskill** [genesis-community/bosh-genesis-kit#110]
Brand new proto deployment created with kit 2.0.1, opting for features:

- bosh-dns-healthcheck
- netop-access

Running `genesis do <env> -- runtime-config` does apply the correct configurations, however it uses `bosh update-config` vs `bosh update-runtime-config`. `update-config` doesn't seem to upload the release(s) in each config while `update-runtime-config` does. While this may be an upstream issue, it nonetheless renders this ineffective as one has to grab each runtime config after the fact and upload each release.

**Comment by ramonskie** [comment]
fixed this in fab4b4146cdc19695dc6af31f66fd5509c2b45ee
