### ISSUE TITLE
Implement SHIELD (agent) feature for Proto BOSHes only

### ISSUE THREAD

**Issue by jhunt** [genesis-community/bosh-genesis-kit#30]
We removed the shield subkit / feature from all Genesis kits when we modernized them, preferring to instead co-locate the SHIELD agent via BOSH runtime-config.  That works great, for everything _except_ the proto-BOSH, which has no runtime-config to fallback on.

Re-enable the `shield` feature, but require the `proto` feature to activate it.  If `shield` is specified without the proto feature, emit a warning to the operator and continue as if the feature flag had not been specified.

**Comment by dennisjbell** [comment]
Is this still something to pursue James?  Did you want it reassigned to someone?
