### ISSUE TITLE
It dose not support selecting/input resource pool for proto-bosh to use 

### ISSUE THREAD

**Issue by xiujiao** [genesis-community/bosh-genesis-kit#35]
Currently the kit does not ask for resource_pool you are using for vsphere. However we can configure resource_pool through `params.vsphere_clusters`.

For example,
```
params:
  vsphere_clusters:
     - my-vsphere-cluster: {resource_pool: other-sphere-res-pool}
```
If kit asks "do you want to configure resource_pool , or add more descriptive words/example on how to configure `params.vsphere_clusters` will be a plus.

**Comment by jhunt** [comment]
What do you have for `params.vsphere_clusters`?
