### ISSUE TITLE
Requesting latest vsphere cpi version in bosh genesis kit

### ISSUE THREAD

**Issue by cwb124** [genesis-community/bosh-genesis-kit#39]
Existing vsphere cpi v45 has a known bug where it only uses the first ephemeral disk in the list of disks in the cpi config.  

https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/issues/108

This issue is fixed in the v50 vsphere cpi.  Thanks!

**Comment by jhunt** [comment]
Addressed in #40 (merged).  Should see a release this morning to fix.

**Comment by Proplex** [comment]
A new version of the BOSH Genesis kit has been released with the #40 fix. You can fetch it via `genesis download-kit bosh/1.1.4`! 😁
