### ISSUE TITLE
Move from raw release to precompiled release

### ISSUE THREAD

**Issue by drnic** [genesis-community/bosh-genesis-kit#4]
In https://github.com/genesis-community/bosh-genesis-kit/blob/master/base/base.yml#L63-L67 we are using the raw uncompiled release. Instead, can we switch to using precompiled releases e.g. https://github.com/genesis-community/bosh-genesis-kit/blob/master/base/base.yml#L63-L67 ?

**Comment by geofffranks** [comment]
Is it possible to specify precompiled releases without knowing precisely which stemcell will be used?

**Comment by drnic** [comment]
Precompiled releases associated with a major stemcell version (e.g. 3363.X)

________________________________

**Comment by drnic** [comment]
For bosh kit, we could use the release + stemcell info from bosh-deployments/bosh.yml

________________________________

**Comment by geofffranks** [comment]
I would rather avoid having to release new versions of a genesis kit for every major stemcell version to be released. The current mechanism lets the operator decide what stemcells they want to be running, or use the pipeline to keep them up to date as new stemcells are released. Having to update kits to keep up to date with newer stemcells
may force them into an undesired upgrade scenario where the kit will bump a release version that they are not ready for yet in production, just to support patching a
vulnerability in a stemcell.

**Comment by rkoster** [comment]
why are stemcell changes special? cf-deployment does not [consider stemcell changes](https://github.com/cloudfoundry/cf-deployment/releases/tag/v0.11.0) to be special. With a kit we say this set of things works, it has passed our ci. We can't promise things we have not tested that's why leaving stemcells out of the pipeline defeats the purpose a bit.

**Comment by geofffranks** [comment]
Why should we be defining what stemcells our end-users can use, and limit their flexibility to do what they want? In theory, stemcell changes shouldn't affect the ability for a boshrelease to function, and which  version you're on seems more of an operational concern than a release concern.

There's also the issue of not all stemcells providing compiled releases and trying to provide end users with a consistent user experience for managing stemcells.

**Comment by rkoster** [comment]
for normal deployments I probably agree, but for `bosh create-env` style deployments using compiled releases improves the user experience considerably (since the deploy time is reduced a lot).

**Comment by geofffranks** [comment]
perhaps we could have genesis trigger logic alongside its stemcell detection for bosh-init/create-env to find the appropriate compiled releases for the versions specified in the kit + the stemcell chosen by the kit + genesis-index metadata?

**Comment by rkoster** [comment]
that would be awsome 👍

**Comment by jhunt** [comment]
This was handled by the move to `bosh-deployment`, upstream.
