### ISSUE TITLE
Sysop feature needs to update SSHD PasswordAuthentication

### ISSUE THREAD

**Issue by krutten** [genesis-community/bosh-genesis-kit#51]
When enabling the Sysop option in the runtime config, login fails because the default sshd_config has the line `PasswordAuthentication no`.  We should look at updating this value if we are adding a sysop user.

**Comment by jhunt** [comment]
I'm assuming this is the Xenial stemcell?  If so, the issue lies in os-conf-release.  Have you checked there to see if an updated version of os-conf handles Xenial properly?

**Comment by xiujiao** [comment]
I remember before we switched to Xenial stemcell, we also had the issue `PasswordAuthentication no`, I do not remember we solved the issue before switched to Xenial or not

**Comment by jhunt** [comment]
The `sysop` user is intended primarily for console access, out-of-band.  For network-based SSH, use the `netop` user.
