### ISSUE TITLE
Kit v1.6.0 has the wrong SHA1 digest for the 621.26 stemcell on AWS.

### ISSUE THREAD

**Issue by elric392** [genesis-community/bosh-genesis-kit#61]
While trying to upgrade to the v1.6.0 of this kit, I ran into the following error.

> Failed to download from 'https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=621.26':
>   Verifying digest for downloaded file:
>     Expected stream to have digest '726fe0188b8b28f85181430409440bd8c1e575a4' but was 'be42b2553538c0d55b1635a59b2cee52cc189c0d'

I have confirmed that the SHA1 digest from bosh.io is ... 'be42b2553538c0d55b1635a59b2cee52cc189c0d' ... for this stemcell.

**Comment by elric392** [comment]
I have also confirmed that the rest of the SHA1 digests are correct for the other IaaS.

**Comment by jhunt** [comment]
Fixed in #62
