### ISSUE TITLE
[1.9.0] credhub-login failed

### ISSUE THREAD

**Issue by drnic** [genesis-community/bosh-genesis-kit#72]
I bumped thunder-dome to v1.9.0 kit but failing to do login:
```
$ genesis do thunder-dome credhub-login
Running credhub-login addon for thunder-dome
./hooks/addon: line 159: _bail: command not found
Could not run 'addon' hook successfully
```

**Comment by VasylTretiakov** [comment]
I might have faced a similar credhub issue recently. If so, the initial questions to answer are as follows:
1. Did the bosh deployment complete successfully or did it present an error at the very end (e.g. in `Waiting for instance 'bosh/0' to be running...` step)?
2. Is TCP connection to the director's port 8844 possible (e.g `nc -v <director_ip> 8844`)?
